/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : AudioLoader_XBEE.H
**     Project   : FlyWeight
**     Processor : MC9S08GT60CFB
**     Beantype  : InterruptVector
**     Version   : Bean 02.022, Driver 01.07, CPU db: 2.87.118
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 6/10/2008, 11:28 AM
**     Abstract  :
**         This bean "InterruptVector" gives an access to interrupt vector.
**         The purpose of this bean is to allocate the interrupt vector
**         in the vector table. Additionally it can provide settings of
**         the interrupt priority register.
**         The interrupt handling routines must be implemented by the user.
**     Settings  :
**         Interrupt vector            : Vtpm2ovf
**         Handle name                 : AudioLoader_OnInterrupt
**         Interrupt request reg.      : TPM2SC    [$0060]
**         Interrupt enable reg.       : TPM2SC    [$0060]
**     Contents  :
**         No public methods
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2006
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

#ifndef __AudioLoader_XBEE
#define __AudioLoader_XBEE

/* MODULE AudioLoader_XBEE. */

#include "PE_types.h"

/*
** ===================================================================
** The interrupt service routine must be implemented by user in one
** of the user modules (see AudioLoader_XBEE.c file for more information).
** ===================================================================
*/
__interrupt void AudioLoader_OnInterrupt(void);

/* END AudioLoader_XBEE. */

#endif /* ifndef __AudioLoader_XBEE */
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.01 [03.92]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
