/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : AudioOut.C
**     Project   : FlyWeight
**     Processor : MC9S08GT60CFB
**     Beantype  : PWM
**     Version   : Bean 02.098, Driver 01.09, CPU db: 2.87.086
**     Compiler  : Metrowerks HCS08 C Compiler
**     Date/Time : 3/27/2006, 12:06 PM
**     Abstract  :
**         This bean implements a pulse-width modulation generator
**         that generates signal with variable duty and fixed cycle. 
**     Settings  :
**         Used output pin             : 
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       18            |  PTD0_TPM1CH0
**             ----------------------------------------------------
**
**         Timer name                  : TPM1 [16-bit] 
**         Counter                     : TPM1CNT   [0031]
**         Mode register               : TPM1SC    [0030]
**         Run register                : TPM1SC    [0030]
**         Prescaler                   : TPM1SC    [0030]
**         Compare register            : TPM1C0V   [0036]
**         Flip-flop register          : TPM1C0SC  [0035]
**
**         Interrupt name              : Vtpm1ch0
**         Interrupt enable reg.       : TPM1C0SC  [0035]
**         User handling procedure     : AudioOut_OnEnd
**         This event is called when the 1 of cycles is generated 
**
**         Port name                   : PTD
**         Bit number (in port)        : 0
**         Bit mask of the port        : 0001
**         Port data register          : PTDD      [000C]
**         Port control register       : PTDDD     [000F]
**
**         Initialization:
**              Output level           : low
**              Timer                  : Enabled
**              Event                  : Enabled
**         High speed mode
**             Prescaler               : divide-by-1
**             Clock                   : 19995429 Hz
**           Initial value of            period     pulse width
**             Xtal ticks              : 32         32
**             microseconds            : 8          8
**             seconds (real)          : 0.0000081  0.0000081
**
**     Contents  :
**         SetRatio16 - byte AudioOut_SetRatio16(word Ratio);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2005
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/


/* MODULE AudioOut. */

#include "Events.h"
#include "PE_Error.h"
#include "AudioOut.h"

#pragma MESSAGE DISABLE C2705          /* WARNING C2705: Possible loss of data */
#pragma MESSAGE DISABLE C5919          /* WARNING C5919: Conversion of floating to unsigned integral */

#pragma MESSAGE DISABLE C4002          /* Disable warning C4002 "Result not used" */

static bool EnMode;                    /* Enable/Disable device in a given speed CPU mode */
static word RatioStore;                /* Ratio of L-level to H-level */
/*
** ===================================================================
**     Method      :  SetRatio (bean PWM)
**
**     Description :
**         The method stores duty value to compare register(s) and sets 
**         necessary bits or (in List mode) call SetReg method for duty 
**         value storing.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void SetRatio(void)
{
  if(RatioStore == 0xFFFF) {           /* Duty = 100%? */
    TPM1C0V = 0xFFFF;                  /* Store new value to the compare reg. */
  } else {
    TPM1C0V = (word)((((dword)TPM1MOD + 0x01) * (dword)RatioStore) >> 0x10); /* Calculate new value of compare register according to the given ratio */
  }
}

/*
** ===================================================================
**     Method      :  AudioOut_SetRatio16 (bean PWM)
**
**     Description :
**         This method sets a new duty-cycle ratio.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Ratio      - Ratio is expressed as an 16-bit unsigned integer
**                      number. 0 - 0xFFFF value is proportional
**                      to ratio 0 - 100%
**         Note: Calculated duty depends on the timer possibilities
**               and on the selected period.
**     Returns     :
**         ---        - Error code
** ===================================================================
*/
byte AudioOut_SetRatio16(word Ratio)
{
  if (!EnMode)                         /* Is the device disabled in the actual speed CPU mode? */
    return ERR_SPEED;                  /* If yes then error */
  RatioStore = Ratio;                  /* Store new value of the ratio */
  SetRatio();                          /* Calculate and set up new appropriate values of the compare and modulo registers */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  AudioOut_Init (bean PWM)
**
**     Description :
**         Initializes the associated peripheral(s) and the beans 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void AudioOut_Init(void)
{
  /* TPM1C0SC: CH0F=0,CH0IE=0,MS0B=1,MS0A=1,ELS0B=1,ELS0A=1,??=0,??=0 */
  TPM1C0SC = 0x3C;                     /* Set up PWM mode with output signal level low */
  RatioStore = 0xFFFF;                 /* Store initial value of the ratio */
  AudioOut_SetHigh();                  /* Initial speed CPU mode is high */
}

/*
** ===================================================================
**     Method      :  AudioOut_SetHigh (bean PWM)
**
**     Description :
**         The method reconfigures the bean and its selected peripheral(s)
**         when the CPU is switched to the High speed mode. The method is 
**         called automatically as s part of the CPU SetHighSpeed method.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void AudioOut_SetHigh(void)
{
  TPM1MOD = 0xA0;
  SetRatio();                          /* Calculate and set up new values of the compare according to the selected speed CPU mode */
  EnMode = TRUE;                       /* Set the flag "device enabled" in the actual speed CPU mode */
  TPM1SC = 0x48;                       /* Run the counter (set CLKSB:CLKSA) */
}

/*
** ===================================================================
**     Method      :  AudioOut_SetLow (bean PWM)
**
**     Description :
**         The method reconfigures the bean and its selected peripheral(s)
**         when the CPU is switched to the Low speed mode. The method is 
**         called automatically as a part of the CPU SetLowSpeed method.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void AudioOut_SetLow(void)
{
  EnMode = FALSE;                      /* Set the flag "device disabled" in the actual speed CPU mode */
}

/*
** ===================================================================
**     Method      :  AudioOut_Interrupt (bean PWM)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes the beans event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(AudioOut_Interrupt)
{
  TPM1SC;
  TPM1SC_TOF = 0;                      /* Reset interrupt request flag */
  AudioOut_OnEnd();                    /* Invoke user event */
}
/* END AudioOut. */

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 2.97 [03.74]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
