/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : AudioLoader_MC1321X.H
**     Project   : FlyWeight
**     Processor : MC13213R2
**     Beantype  : InterruptVector
**     Version   : Bean 02.022, Driver 01.07, CPU db: 2.87.123
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 8/16/2008, 12:14 PM
**     Abstract  :
**         This bean "InterruptVector" gives an access to interrupt vector.
**         The purpose of this bean is to allocate the interrupt vector
**         in the vector table. Additionally it can provide settings of
**         the interrupt priority register.
**         The interrupt handling routines must be implemented by the user.
**     Settings  :
**         Interrupt vector            : Vtpm1ovf
**         Handle name                 : AudioLoader_OnInterrupt
**         Interrupt request reg.      : TPM1SC    [$0030]
**         Interrupt enable reg.       : TPM1SC    [$0030]
**     Contents  :
**         No public methods
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2006
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

#ifndef __AudioLoader_MC1321X
#define __AudioLoader_MC1321X

/* MODULE AudioLoader_MC1321X. */

#include "PE_types.h"

/*
** ===================================================================
** The interrupt service routine must be implemented by user in one
** of the user modules (see AudioLoader_MC1321X.c file for more information).
** ===================================================================
*/
__interrupt void AudioLoader_OnInterrupt(void);

/* END AudioLoader_MC1321X. */

#endif /* ifndef __AudioLoader_MC1321X */
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.01 [03.92]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
