/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : GPIO1.C
**     Project   : FlyWeight
**     Processor : MC13213R2
**     Beantype  : Init_GPIO
**     Version   : Bean 01.025, Driver 01.12, CPU db: 2.87.125
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 11/25/2009, 3:49 PM
**     Abstract  :
**          This file implements the General Purpose Input Output (PTA)
**          module initialization according to the Peripheral Initialization
**          Bean settings, and defines interrupt service routines prototypes.
**
**     Settings  :
**          Bean name                                      : GPIO1
**          Device                                         : PTA
**          Port control                                   : Individual pins
**
**          Used pins                                      :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       0             |  PTA0_KBIP0
**                       1             |  PTA1_KBIP1
**                       2             |  PTA2_KBIP2
**                       3             |  PTA3_KBIP3
**                       4             |  PTA4_KBIP4
**             ----------------------------------------------------
**
**          Pin0                                           : PTA0_KBIP0
**            Direction                                    : Output
**            Output value                                 : no initialization
**            Pull resistor                                : no initialization
**            Open drain                                   : push-pull
**
**          Pin1                                           : PTA1_KBIP1
**            Direction                                    : Input
**            Output value                                 : no initialization
**            Pull resistor                                : no initialization
**            Open drain                                   : push-pull
**
**          Pin2                                           : PTA2_KBIP2
**            Direction                                    : Input
**            Output value                                 : no initialization
**            Pull resistor                                : no initialization
**            Open drain                                   : push-pull
**
**          Pin3                                           : PTA3_KBIP3
**            Direction                                    : Input
**            Output value                                 : no initialization
**            Pull resistor                                : no initialization
**            Open drain                                   : push-pull
**
**          Pin4                                           : PTA4_KBIP4
**            Direction                                    : Input
**            Output value                                 : no initialization
**            Pull resistor                                : no initialization
**            Open drain                                   : push-pull
**
**          Call Init method                               : yes
**     Contents  :
**         Init - void GPIO1_Init(void);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2008
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

/* MODULE GPIO1. */

#include "GPIO1.h"
/*
** ===================================================================
**     Method      :  GPIO1_Init (bean Init_GPIO)
**
**     Description :
**         This method initializes registers of the GPIO module
**         according to this Peripheral Initialization Bean settings.
**         Call this method in the user code to initialize the
**         module. By default, the method is called by PE
**         automatically; see "Call Init method" property of the
**         bean for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void GPIO1_Init(void)
{
  /* PTADD: PTADD4=0,PTADD3=0,PTADD2=0,PTADD1=0,PTADD0=1 */
  clrSetReg8Bits(PTADD, 0x1E, 0x01);    
}

/* END GPIO1. */

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.03 [04.07]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
