/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : KBI.C
**     Project   : FlyWeight
**     Processor : MC9S08GT60CFB
**     Beantype  : Init_KBI
**     Version   : Bean 01.009, Driver 01.01, CPU db: 2.87.086
**     Compiler  : Metrowerks HCS08 C Compiler
**     Date/Time : 9/20/2007, 2:38 PM
**     Abstract  :
**          This file implements the KBI (KBI1) module initialization
**          according to the Peripheral Initialization Bean settings, and defines
**          interrupt service routines prototypes.
**          The KBI module is the serial peripheral interface module,which allows 
**          full-duplex, synchronous, serial communications with peripheral devices.
**          The keyboard interrupt module (KBI) provides a few independently maskable 
**          external interrupts. When a port pin is enabled for keyboard interrupt 
**          function, an internal pullup/pulldown device is also enabled on the pin.

**     Settings  :
**          Bean name                                      : KBI
**          Device                                         : KBI1
**          Settings 
**            Triggering sensitivity                       : edge and level
**          Pins 
**            Pin0                                         : Disabled
**            Pin1                                         : Disabled
**            Pin2                                         : Disabled
**            Pin3                                         : Disabled
**            Pin4                                         : Disabled
**            Pin5                                         : Enabled
**              Pin                                        : PTA5_KBI1P5
**              Pin signal                                 : 
**            Pin6                                         : Enabled
**              Pin                                        : PTA6_KBI1P6
**              Pin signal                                 : 
**            Pin7                                         : Disabled
**          Interrupts 
**            Keyboard request 
**              Interrupt                                  : Vkeyboard1
**              Keyboard request interrupt                 : Disabled
**              ISR name                                   : keyboardISR
**          Initialization 
**            Call Init method                             : yes
**     Contents  :
**         Init - void KBI_Init(void);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2005
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

/* MODULE KBI. */

#include "KBI.h"

/*
** ###################################################################
**
**  The interrupt service routine(s) must be implemented
**  by user in one of the following user modules.
**
**  If the "Generate ISR" option is enabled, Processor Expert generates
**  ISR templates in the CPU event module.
**
**  User modules:
**      FlyWeight.c
**
** ###################################################################

ISR( keyboardISR)
{
  // NOTE: The routine should include the following actions to obtain
  //       correct functionality of the hardware.
  //
  //  Keyboard Interrupt Flag is cleared by writing a 1 to the 
  //  KBACK control bit. 
  // Example:   KBI1SC = 4
  //          

}

*/

/*
** ===================================================================
**     Method      :  KBI_Init (bean Init_KBI)
**
**     Description :
**         This method initializes registers of the KBI module
**         according to this Peripheral Initialization Bean settings.
**         Call this method in user code to initialize the module.
**         By default, the method is called by PE automatically; see
**         "Call Init method" property of the bean for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void KBI_Init(void)
{
  /* KBI1SC: KBIE=0 */
  clrReg8Bits(KBI1SC, 0x02);            
  /* KBI1PE: KBIPE7=0,KBIPE6=1,KBIPE5=1,KBIPE4=0,KBIPE3=0,KBIPE2=0,KBIPE1=0,KBIPE0=0 */
  setReg8(KBI1PE, 0x60);                
  /* KBI1SC: KBEDG6=1,KBEDG5=1,KBIMOD=1 */
  setReg8Bits(KBI1SC, 0x61);            

  /* KBI1SC: KBACK=1 */
  setReg8Bits(KBI1SC, 0x04);            
  /* KBI1SC: KBIE=0 */
  clrReg8Bits(KBI1SC, 0x02);            
}

/* END KBI. */

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 2.97 [03.74]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
