/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : PWM_EVB.H
**     Project   : FlyWeight
**     Processor : MC9S08GT60CFD
**     Beantype  : Init_TPM
**     Version   : Bean 01.035, Driver 01.07, CPU db: 2.87.074
**     Compiler  : Metrowerks HCS08 C Compiler
**     Date/Time : 1/30/2008, 5:51 PM
**     Abstract  :
**          This file implements the TPM (TPM1) module initialization
**          according to the Peripheral Initialization Bean settings,
**          and defines interrupt service routines prototypes.
**     Settings  :
**          Bean name                                      : PWM_EVB
**          Device                                         : TPM1
**          Settings
**            Clock settings
**              Clock Source Select                        : Bus rate clock
**              Prescaler                                  : 1
**              Modulo Counter                             : 255
**              Period                                     : 12.8 us
**            Aligned                                      : Left
**          Channels                                       : 1
**            Channel0                                     : 1
**              Capture/compare device                     : TPM12
**              Settings
**                Mode                                     : PWM
**                  PWM Output Action                      : Clear output on compare
**                  ChannelValue                           : 0
**                  DutyCycle                              : 0 us
**              Pin                                        : Used
**                Channel Pin                              : PTD2_TPM1CH2
**                Channel Pin Signal                       : 
**                Pull Resistor                            : autoselected pull
**              Interrupt
**                Channel Interrupt
**                  Interrupt                              : Vtpm1ch2
**                  Channel Interrupt                      : Disabled
**                  ISR Name                               : 
**          Pins
**            External Clock Source                        : Disabled
**          Interrupts
**            Overflow Interrupt
**              Interrupt                                  : Vtpm1ovf
**              Overflow Interrupt                         : Disabled
**              ISR Name                                   :
**          Initialization
**          Call Init Method                               : no
**     Contents  :
**         Init - void PWM_EVB_Init(void);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2005
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

#ifndef __PWM_EVB
#define __PWM_EVB

/* MODULE PWM_EVB. */

#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"

/*
** ===================================================================
**     Method      :  PWM_EVB_Init (bean Init_TPM)
**
**     Description :
**         This method initializes registers of the TPM module
**         according to this Peripheral Initialization Bean settings.
**         Call this method in the user code to initialize the
**         module. By default, the method is called by PE
**         automatically; see "Call Init method" property of the
**         bean for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void PWM_EVB_Init(void);

/* END PWM_EVB. */

#endif /* ifndef __PWM_EVB */
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 2.97 [03.74]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
