/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : PWM_MC1321X.H
**     Project   : FlyWeight
**     Processor : MC13213R2
**     Beantype  : Init_TPM
**     Version   : Bean 01.053, Driver 01.12, CPU db: 2.87.123
**     Compiler  : CodeWarrior HCS08 C Compiler
**     Date/Time : 8/18/2008, 12:47 PM
**     Abstract  :
**          This file implements the TPM (TPM2) module initialization
**          according to the Peripheral Initialization Bean settings,
**          and defines interrupt service routines prototypes.
**     Settings  :
**          Bean name                                      : PWM_MC1321X
**          Device                                         : TPM2
**          Settings
**            Clock settings
**              Clock Source Select                        : Bus rate clock
**              Prescaler                                  : 1
**              Modulo Counter                             : 255
**              Period                                     : 12.8 us
**            Aligned                                      : Left
**          Channels                                       : 2
**            Channel0                                     : 1
**              Capture/compare device                     : TPM22
**              Settings
**                Mode                                     : PWM
**                  PWM Output Action                      : Clear output on compare
**                  ChannelValue                           : 0
**                  DutyCycle                              : 0 us
**              Pin                                        : Used
**                Channel Pin                              : PTD5_TPM2CH2
**                Channel Pin Signal                       : 
**                Pull Resistor                            : autoselected pull
**              Interrupt
**                Channel Interrupt
**                  Interrupt                              : Vtpm2ch2
**                  Channel Interrupt                      : Disabled
**                  ISR Name                               : 
**            Channel1                                     : 2
**              Capture/compare device                     : TPM23
**              Settings
**                Mode                                     : PWM
**                  PWM Output Action                      : Clear output on compare
**                  ChannelValue                           : 0
**                  DutyCycle                              : 0 us
**              Pin                                        : Used
**                Channel Pin                              : PTD6_TPM2CH3
**                Channel Pin Signal                       : 
**                Pull Resistor                            : autoselected pull
**              Interrupt
**                Channel Interrupt
**                  Interrupt                              : Vtpm2ch3
**                  Channel Interrupt                      : Disabled
**                  ISR Name                               : 
**          Pins
**            External Clock Source                        : Disabled
**          Interrupts
**            Overflow Interrupt
**              Interrupt                                  : Vtpm2ovf
**              Overflow Interrupt                         : Disabled
**              ISR Name                                   :
**          Initialization
**          Call Init Method                               : yes
**     Contents  :
**         Init - void PWM_MC1321X_Init(void);
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2006
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

#ifndef __PWM_MC1321X
#define __PWM_MC1321X

/* MODULE PWM_MC1321X. */

#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"

/*
** ===================================================================
**     Method      :  PWM_MC1321X_Init (bean Init_TPM)
**
**     Description :
**         This method initializes registers of the TPM module
**         according to this Peripheral Initialization Bean settings.
**         Call this method in the user code to initialize the
**         module. By default, the method is called by PE
**         automatically; see "Call Init method" property of the
**         bean for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void PWM_MC1321X_Init(void);

/* END PWM_MC1321X. */

#endif /* ifndef __PWM_MC1321X */
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 3.01 [03.92]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
