/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Vectors.C
**     Project   : FlyWeight
**     Processor : MC9S08GT60CFB
**     Version   : Bean 01.101, Driver 01.21, CPU db: 2.87.086
**     Compiler  : Metrowerks HCS08 C Compiler
**     Date/Time : 9/20/2007, 3:35 PM
**     Abstract  :
**         This bean "MC9S08GT60_44" contains initialization of the
**         CPU and provides basic methods and events for CPU core
**         settings.
**     Settings  :
**
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2005
**     UNIS, spol. s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/


#include "Cpu.h"
#include "RTI1.h"
#include "SWI.h"
#include "MC13191IRQ.h"
#include "PWM_XBee.h"
#include "AudioOut.h"
#include "KBI.h"
extern void _EntryPoint(void);

void (* const _vect[])() @0xFFCC = {   /* Interrupt vector table */
         dispatchRTI,                  /* Int.no.  0 Vrti (at FFCC)                  Used */
         Cpu_Interrupt,                /* Int.no.  1 Viic1 (at FFCE)                 Unassigned */
         Cpu_Interrupt,                /* Int.no.  2 Vatd1 (at FFD0)                 Unassigned */
         keyboardISR,                  /* Int.no.  3 Vkeyboard1 (at FFD2)            Used */
         Cpu_Interrupt,                /* Int.no.  4 Vsci2tx (at FFD4)               Unassigned */
         Cpu_Interrupt,                /* Int.no.  5 Vsci2rx (at FFD6)               Unassigned */
         Cpu_Interrupt,                /* Int.no.  6 Vsci2err (at FFD8)              Unassigned */
         Cpu_Interrupt,                /* Int.no.  7 Vsci1tx (at FFDA)               Unassigned */
         Cpu_Interrupt,                /* Int.no.  8 Vsci1rx (at FFDC)               Unassigned */
         Cpu_Interrupt,                /* Int.no.  9 Vsci1err (at FFDE)              Unassigned */
         Cpu_Interrupt,                /* Int.no. 10 Vspi1 (at FFE0)                 Unassigned */
         AudioLoader_OnInterrupt,      /* Int.no. 11 Vtpm2ovf (at FFE2)              Used */
         Cpu_Interrupt,                /* Int.no. 12 Reserved12 (at FFE4)            Unassigned */
         Cpu_Interrupt,                /* Int.no. 13 Reserved13 (at FFE6)            Unassigned */
         Cpu_Interrupt,                /* Int.no. 14 Reserved14 (at FFE8)            Unassigned */
         Cpu_Interrupt,                /* Int.no. 15 Vtpm2ch1 (at FFEA)              Unassigned */
         Cpu_Interrupt,                /* Int.no. 16 Vtpm2ch0 (at FFEC)              Unassigned */
         Cpu_Interrupt,                /* Int.no. 17 Vtpm1ovf (at FFEE)              Unassigned */
         Cpu_Interrupt,                /* Int.no. 18 Reserved18 (at FFF0)            Unassigned */
         Cpu_Interrupt,                /* Int.no. 19 Vtpm1ch1 (at FFF2)              Unassigned */
         Cpu_Interrupt,                /* Int.no. 20 Vtpm1ch0 (at FFF4)              Unassigned */
         Cpu_OnClockMonitorInt,        /* Int.no. 21 Vicg (at FFF6)                  Used */
         Cpu_Interrupt,                /* Int.no. 22 Vlvd (at FFF8)                  Unassigned */
         IRQIsr,                       /* Int.no. 23 Virq (at FFFA)                  Used */
         vPortYield,                   /* Int.no. 24 Vswi (at FFFC)                  Used */
         _EntryPoint                   /* Int.no. 25 Vreset (at FFFE)                Reset vector */
 };
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 2.97 [03.74]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
