/*
 * crc.h
 *
 * Code generated by universal_crc by Danjel McGougan
 *
 * CRC parameters used:
 *   bits:       7
 *   poly:       0x45
 *   init:       0x00
 *   xor:        0x00
 *   reverse:    false
 *   non-direct: false
 *
 * CRC of the string "123456789" is 0x61
 */

#ifndef CRC_H_
#define CRC_H_

//#include <stddef.h>
//#include <stdint.h>
#include "gwTypes.h"

gwUINT8 crc_calc(const gwUINT8 *data, gwUINT8 len);

extern const gwUINT8 crc_table[256];

static inline gwUINT8 crc_init(void)
{
	return 0;
}

static inline gwUINT8 crc_next(gwUINT8 crc, gwUINT8 data)
{
	return crc_table[crc ^ data];
}

static inline gwUINT8 crc_final(gwUINT8 crc)
{
	return (crc >> 1);
}

#endif
