/*
   FlyWeight
   © Copyright 2005, 2006 Jeffrey B. Williams
   All rights reserved
   
   $Id$
   $Name$	
*/

// --------------------------------------------------------------------------
// Kernel includes

#include "FreeRTOS.h"
#include "task.h"
#include "pub_def.h"
#include "mcu_hw_config.h"
#include "MC13192_hw_config.h"
#include "simple_mac.h"
#include "xbeeinit.h"
#include "remoteRadioTask.h"
#include "ledBlinkTask.h"
#include "commands.h"
//#include "WatchDog.h"

extern xQueueHandle gRadioTransmitQueue;
extern xQueueHandle gRadioReceiveQueue;
extern xQueueHandle gLEDBlinkQueue;

RemoteStateType		gRemoteState;

// --------------------------------------------------------------------------
// This is called from the main() function generated by the Processor Expert.

void vMain( void ) {

	gRemoteState = eRemoteStateInit;

	// These got moved into PE pre-init, so that the RTI clock can use the EXTAL.
	// The EXTAL has to be setup and reserved BEFORE initialization of the ICG in PE init.
//	MCUInit();
//	MC13192Init();
//	MLMESetMC13192ClockRate(0);
#ifdef XBEE
	xbeeInit();
#endif
	MLMEMC13192PAOutputAdjust(MAX_POWER);
	if (MLMESetChannelRequest(15) == SUCCESS) {}

	/* Start the task that will handle the radio */
	xTaskCreate(radioTransmitTask, (const signed portCHAR * const) "RadioTransmit", configMINIMAL_STACK_SIZE, NULL, RADIO_PRIORITY, NULL );
	xTaskCreate(radioReceiveTask, (const signed portCHAR * const) "RadioReceive", configMINIMAL_STACK_SIZE, NULL, RADIO_PRIORITY, NULL );
#if  defined(MC13192EVB) || defined (MC13192SARD)
	xTaskCreate(LEDBlinkTask, (const signed portCHAR * const) "LED Blink", configMINIMAL_STACK_SIZE, NULL, LED_BLINK_PRIORITY, NULL );
#endif

	gRadioReceiveQueue = xQueueCreate(RX_QUEUE_SIZE, (unsigned portBASE_TYPE) sizeof(ERadioState));
	gRadioTransmitQueue = xQueueCreate(RX_QUEUE_SIZE, sizeof(BufferCntType));
	gLEDBlinkQueue = xQueueCreate(LED_BLINK_QUEUE_SIZE, (unsigned portBASE_TYPE) sizeof(UINT8));

	// Setup the SMAC glue.
	initSMACRadioQueueGlue(gRadioReceiveQueue);

	/* All the tasks have been created - start the scheduler. */
//	WatchDog_Clear();
	vTaskStartScheduler();
	
	/* Should not reach here! */
	for ( ;; );
}

// --------------------------------------------------------------------------

#define SAMPLE_CORRECTION	0x151
#define SAMPLE_RATE			0x3f3

void vApplicationIdleHook( void ) {
	// Clear the watchdog timer.
//	WatchDog_Clear();

}
