/*
   FlyWeight
   © Copyright 2005, 2006 Jeffrey B. Williams
   All rights reserved
   
   $Id$
   $Name$	
*/

// --------------------------------------------------------------------------
// Kernel includes

#include "FreeRTOS.h"
#include "task.h"
#include "pub_def.h"
#include "mcu_hw_config.h"
#include "MC13192_hw_config.h"
#include "simple_mac.h"
#include "xbeeinit.h"
#include "remoteRadioTask.h"
#include "ledBlinkTask.h"
//#include "WatchDog.h"

xQueueHandle xRadioTransmitQueue;
xQueueHandle xRadioReceiveQueue;
xQueueHandle xLEDBlinkQueue;

// --------------------------------------------------------------------------
// This is called from the main() function generated by the Processor Expert.

void vMain( void ) {

//	WatchDog_Clear();
//	MCUInit();
//	MC13192Init();
//	MLMESetMC13192ClockRate(0);
#ifdef XBEE
	xbeeInit();
#endif
	MLMEMC13192PAOutputAdjust(MAX_POWER);
	if (MLMESetChannelRequest(15) == SUCCESS) {}

	/* Start the task that will handle the radio */
//	xTaskCreate( vRadioTransmitTask, (const signed portCHAR * const) "RadioTransmit", configMINIMAL_STACK_SIZE, NULL, RADIO_PRIORITY, NULL );
	xTaskCreate( vRadioReceiveTask, (const signed portCHAR * const) "RadioReceive", configMINIMAL_STACK_SIZE, NULL, RADIO_PRIORITY, NULL );
#if  defined(MC13192EVB) || defined (MC13192SARD)
	xTaskCreate( vLEDBlinkTask, (const signed portCHAR * const) "LED Blink", configMINIMAL_STACK_SIZE, NULL, LED_BLINK_PRIORITY, NULL );
#endif

	xRadioReceiveQueue = xQueueCreate(RADIO_QUEUE_SIZE, (unsigned portBASE_TYPE) sizeof(ERadioState));
	xRadioTransmitQueue = xQueueCreate(RADIO_QUEUE_SIZE, sizeof(BufferCntType));
	xLEDBlinkQueue = xQueueCreate(LED_BLINK_QUEUE_SIZE, (unsigned portBASE_TYPE) sizeof(UINT8));

	// Setup the SMAC glue.
	initSMACRadioQueueGlue(xRadioReceiveQueue);

	/* All the tasks have been created - start the scheduler. */
//	WatchDog_Clear();
	vTaskStartScheduler();
	
	/* Should not reach here! */
	for ( ;; );
}

// --------------------------------------------------------------------------

#define SAMPLE_CORRECTION	0x151
#define SAMPLE_RATE			0x3f3

void vApplicationIdleHook( void ) {
	// Clear the watchdog timer.
//	WatchDog_Clear();

	// The TPM2CH1 counter can "miss" it's shot due to the way PE share the counter.
	// This makes the audio sampling sound like crap.  Attempt to "fix" this by setting
	// the counter to 1/2 the cycle time of the audio sampling.

/*	bool  fireNow = FALSE;
	
	if (TPM2C1V < TPM2CNT) {
		if ((TPM2CNT + SAMPLE_RATE) < TPM2C1V) {
			fireNow = TRUE;	
		}
	} else if ((TPM2CNT + SAMPLE_RATE) < TPM2C1V) {
		fireNow = TRUE;
	}
	
	if (fireNow == TRUE)
		TPM2C1V = TPM2CNT + 30;
*/
}
